./psp_conv -v --cmp SVL/BARBALI
./psp_conv -v --cmp SVL/BASIRISK
./psp_conv -v --cmp SVL/CARD_DEM
./psp_conv -v --cmp SVL/CARD_GOL
./psp_conv -v --cmp SVL/CARD_GRI
./psp_conv -v --cmp SVL/CARD_RYO
./psp_conv -v --cmp SVL/CARD_TAR
./psp_conv -v --cmp SVL/CARDKISI
./psp_conv -v --cmp SVL/CENTOURS
./psp_conv -v --cmp SVL/DEM_GOL
./psp_conv -v --cmp SVL/DODO
./psp_conv -v --cmp SVL/DOPELGEN
./psp_conv -v --cmp SVL/DRA_NAKU
./psp_conv -v --cmp SVL/DRAGON
./psp_conv -v --cmp SVL/E_EDW_VO
./psp_conv -v --cmp SVL/E_GEP_VO
./psp_conv -v --cmp SVL/E_GRA_VO
./psp_conv -v --cmp SVL/E_PRO_VO
./psp_conv -v --cmp SVL/EDO_DP_D
./psp_conv -v --cmp SVL/EDO_DP_G
./psp_conv -v --cmp SVL/EDW_VO
./psp_conv -v --cmp SVL/EYE
./psp_conv -v --cmp SVL/FLOGER
./psp_conv -v --cmp SVL/GHOST
./psp_conv -v --cmp SVL/GOBRIN
./psp_conv -v --cmp SVL/GRA_VO
./psp_conv -v --cmp SVL/GURIFON
./psp_conv -v --cmp SVL/KAGEOU
./psp_conv -v --cmp SVL/KAIZOKU
./psp_conv -v --cmp SVL/MIKONID
./psp_conv -v --cmp SVL/NIGHT
./psp_conv -v --cmp SVL/NIGT_GOL
./psp_conv -v --cmp SVL/POLTER
./psp_conv -v --cmp SVL/POT_VO
./psp_conv -v --cmp SVL/PRO_VO
./psp_conv -v --cmp SVL/RALVA
./psp_conv -v --cmp SVL/RYO_EDW
./psp_conv -v --cmp SVL/RYO_POT
./psp_conv -v --cmp SVL/S_DANSIO
./psp_conv -v --cmp SVL/S_DOUKUTU
./psp_conv -v --cmp SVL/S_ERIEL
./psp_conv -v --cmp SVL/S_FILESL
./psp_conv -v --cmp SVL/S_FUNE
./psp_conv -v --cmp SVL/S_HAKABA
./psp_conv -v --cmp SVL/S_KAGEOU
./psp_conv -v --cmp SVL/S_MAOU
./psp_conv -v --cmp SVL/S_MIZU
./psp_conv -v --cmp SVL/S_MORI
./psp_conv -v --cmp SVL/S_SIRO
./psp_conv -v --cmp SVL/S_TOROKO
./psp_conv -v --cmp SVL/SAMANSA
./psp_conv -v --cmp SVL/SIRENE
./psp_conv -v --cmp SVL/SRIME
./psp_conv -v --cmp SVL/TARNCYRA
./psp_conv -v --cmp SVL/UNDEAD
./psp_conv -v --cmp SVL/VORGRODO
./psp_conv -v --cmp SVL/WARUERU
./psp_conv -v --cmp SVL/WARUGODA

