./psp_conv -v -w SOUND/BARBALI
./psp_conv -v -w SOUND/BASIRISK
./psp_conv -v -w SOUND/CARD_DEM
./psp_conv -v -w SOUND/CARD_GOL
./psp_conv -v -w SOUND/CARD_GRI
./psp_conv -v -w SOUND/CARD_RYO
./psp_conv -v -w SOUND/CARD_TAR
./psp_conv -v -w SOUND/CARDKISI
./psp_conv -v -w SOUND/CENTOURS
./psp_conv -v -w SOUND/DEM_GOL
./psp_conv -v -w SOUND/DODO
./psp_conv -v -w SOUND/DOPELGEN
./psp_conv -v -w SOUND/DRA_NAKU
./psp_conv -v -w SOUND/DRAGON
./psp_conv -v -w SOUND/E_EDW_VO
./psp_conv -v -w SOUND/E_GEP_VO
./psp_conv -v -w SOUND/E_GRA_VO
./psp_conv -v -w SOUND/E_PRO_VO
./psp_conv -v -w SOUND/EDO_DP_D
./psp_conv -v -w SOUND/EDO_DP_G
./psp_conv -v -w SOUND/EDW_VO
./psp_conv -v -w SOUND/EYE
./psp_conv -v -w SOUND/FLOGER
./psp_conv -v -w SOUND/GHOST
./psp_conv -v -w SOUND/GOBRIN
./psp_conv -v -w SOUND/GRA_VO
./psp_conv -v -w SOUND/GURIFON
./psp_conv -v -w SOUND/KAGEOU
./psp_conv -v -w SOUND/KAIZOKU
./psp_conv -v -w SOUND/MAINMAP
./psp_conv -v -w SOUND/MIKONID
./psp_conv -v -w SOUND/NIGHT
./psp_conv -v -w SOUND/NIGT_GOL
./psp_conv -v -w SOUND/NISEPO
./psp_conv -v -w SOUND/POLTER
./psp_conv -v -w SOUND/POT_VO
./psp_conv -v -w SOUND/PRO_VO
./psp_conv -v -w SOUND/RALVA
./psp_conv -v -w SOUND/RIYON
./psp_conv -v -w SOUND/RYO_EDW
./psp_conv -v -w SOUND/RYO_POT
./psp_conv -v -w SOUND/S_DANSIO
./psp_conv -v -w SOUND/S_DOUKUTU
./psp_conv -v -w SOUND/S_ERIEL
./psp_conv -v -w SOUND/S_FILESL
./psp_conv -v -w SOUND/S_FUNE
./psp_conv -v -w SOUND/S_HAKABA
./psp_conv -v -w SOUND/S_KAGEOU
./psp_conv -v -w SOUND/S_MAOU
./psp_conv -v -w SOUND/S_MIZU
./psp_conv -v -w SOUND/S_MORI
./psp_conv -v -w SOUND/S_SIRO
./psp_conv -v -w SOUND/S_TOROKO
./psp_conv -v -w SOUND/SAMANSA
./psp_conv -v -w SOUND/SIRENE
./psp_conv -v -w SOUND/SRIME
./psp_conv -v -w SOUND/TARNCYRA
./psp_conv -v -w SOUND/UNDEAD
./psp_conv -v -w SOUND/VORGRODO
./psp_conv -v -w SOUND/WARUERU
./psp_conv -v -w SOUND/WARUGODA

