./psp_conv --info AT3/ASERU.AT3
./psp_conv --info AT3/BATTLE1.AT3
./psp_conv --info AT3/BATTLE2.AT3
./psp_conv --info AT3/BATTLE3.AT3
./psp_conv --info AT3/BATTLE4.AT3
./psp_conv --info AT3/BATTLE5.AT3
./psp_conv --info AT3/BATTLE82.AT3
./psp_conv --info AT3/BATTLE83.AT3
./psp_conv --info AT3/BATTLE89.AT3
./psp_conv --info AT3/CATCHI.AT3
./psp_conv --info AT3/ELFER.AT3
./psp_conv --info AT3/ENDING.AT3
./psp_conv --info AT3/GOBLIN.AT3
./psp_conv --info AT3/K_AMORI.AT3
./psp_conv --info AT3/K_DOKUTU.AT3
./psp_conv --info AT3/K_DOWERF.AT3
./psp_conv --info AT3/K_FILE.AT3
./psp_conv --info AT3/K_FMORI.AT3
./psp_conv --info AT3/K_FUNE.AT3
./psp_conv --info AT3/K_FUNE2.AT3
./psp_conv --info AT3/K_HAKABA.AT3
./psp_conv --info AT3/K_IWABA.AT3
./psp_conv --info AT3/K_KMORI.AT3
./psp_conv --info AT3/K_MAKAI.AT3
./psp_conv --info AT3/K_MIZUUM.AT3
./psp_conv --info AT3/K_SOUGEN.AT3
./psp_conv --info AT3/K_TOU.AT3
./psp_conv --info AT3/K_UMI.AT3
./psp_conv --info AT3/KURUTON.AT3
./psp_conv --info AT3/MACHI.AT3
./psp_conv --info AT3/MAHOU.AT3
./psp_conv --info AT3/OPENING2.AT3
./psp_conv --info AT3/PLAYER58.AT3
./psp_conv --info AT3/PLAYER64.AT3
./psp_conv --info AT3/PLAYER66.AT3
./psp_conv --info AT3/PLAYER71.AT3
./psp_conv --info AT3/PLAYER72.AT3
./psp_conv --info AT3/PLAYER73.AT3
./psp_conv --info AT3/PLAYER74.AT3
./psp_conv --info AT3/PLAYER75.AT3
./psp_conv --info AT3/PLAYER78.AT3
./psp_conv --info AT3/PLAYER82.AT3
./psp_conv --info AT3/PLAYER83.AT3
./psp_conv --info AT3/PLAYER84.AT3
./psp_conv --info AT3/SND0.AT3
./psp_conv --info AT3/STAFFROLL.AT3
./psp_conv --info AT3/THEME.AT3
./psp_conv --info AT3/YADOYA.AT3
./psp_conv --info AT3/ZAKKAYA.AT3
